name: weather
description: Application for viewing the weather.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true